### ISSUE TITLE
Error importing _imaging as core

### ISSUE THREAD

**Issue by CaliHoya** [justinlittman/fb-ad-archive-scraper#1]
Tried to run the scraper in a virtual environment, but got this error:

`Traceback (most recent call last):
  File "scraper.py", line 4, in <module>
    from PIL import Image
  File "/Users/*****/Environments/Fb-ad-archive-scraper/lib/python3.6/site-packages/PIL/Image.py", line 60, in <module>
    from . import _imaging as core
ImportError: dlopen(/Users/*****/Environments/Fb-ad-archive-scraper/lib/python3.6/site-packages/PIL/_imaging.cpython-36m-darwin.so, 2): Symbol not found: _clock_gettime
  Referenced from: /Users/*****/Environments/Fb-ad-archive-scraper/lib/python3.6/site-packages/PIL/.dylibs/liblzma.5.dylib (which was built for Mac OS X 10.12)
  Expected in: /usr/lib/libSystem.B.dylib
 in /Users/*****/Environments/Fb-ad-archive-scraper/lib/python3.6/site-packages/PIL/.dylibs/liblzma.5.dylib`

**Comment by CaliHoya** [comment]
I think this may be the issue as I was using MAC OS 10.10:

https://github.com/python-pillow/Pillow/issues/3068

Will try to upgrade and see if it fixes it. Any help appreciated!

**Comment by CaliHoya** [comment]
Upgrading allowed the log in to Facebook to begin properly, but I am now getting another error when logging in (perhaps related to the email):

`Logging into Facebook
Traceback (most recent call last):
  File "scraper.py", line 277, in <module>
    main(' '.join(args.query), args.email, args.password, ad_limit=args.limit, headless=not args.headed)
  File "scraper.py", line 141, in main
    driver.find_element_by_name('email').send_keys(fb_email)
  File "/Users/**********/Environments/Fb-ad-archive-scraper/lib/python3.6/site-packages/selenium/webdriver/remote/webelement.py", line 479, in send_keys
    'value': keys_to_typing(value)})
  File "/Users/**********/Environments/Fb-ad-archive-scraper/lib/python3.6/site-packages/selenium/webdriver/remote/webelement.py", line 628, in _execute
    return self._parent.execute(command, params)
  File "/Users/**********/Environments/Fb-ad-archive-scraper/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 314, in execute
    self.error_handler.check_response(response)
  File "/Users/**********/Environments/Fb-ad-archive-scraper/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: call function result missing 'value'
`

The command I'm running to launch the script is: 
`python3 scraper.py email@gmail.com password pelosi
`

**Comment by justinlittman** [comment]
Which version of chromedriver are you running? `chromedriver --version`
What version of chrome?
What version of selenium? `pip freeze | grep selenium`

Thanks!

**Comment by CaliHoya** [comment]
Which version of chromedriver are you running? ChromeDriver 2.33.506106
What version of chrome? Version 67.0.3396.99
What version of selenium? 3.12.0

Thank you for the help!

**Comment by justinlittman** [comment]
Can you trying upgrading ChromeDriver to 2.40? What environment are you running this in? Will see if I can replicate.

**Comment by CaliHoya** [comment]
Upgrading ChromeDriver solved the issue - thanks!

Side note: the images have a header bar that obscures the top of the ad.


[image: ad-0339.png]

**Comment by justinlittman** [comment]
Super. Can you attach one of the problematic images?

**Comment by CaliHoya** [comment]
![ad-0339](https://user-images.githubusercontent.com/5186155/42786839-9f35ec50-890c-11e8-8066-ae4630d10698.png)

![ad-0282](https://user-images.githubusercontent.com/5186155/42786844-a6a5e918-890c-11e8-9c2f-689b6f00884f.png)

**Comment by justinlittman** [comment]
Hmmm ... What OS are you using?

**Comment by neshg** [comment]
I am getting Login failed error

**Comment by justinlittman** [comment]
FB made the search box have a fixed position as well. Working on a fix.
