### ISSUE TITLE
Search bar obstructing ad creative

### ISSUE THREAD

**Issue by jakelowen** [justinlittman/fb-ad-archive-scraper#3]
First off, Amazing code. Thank you!   All the screenshots are obstructed near the top by the search bar. 

Is there a way to modify CSS to hide that search bar before taking a screenshot?  

See image:
![image](https://user-images.githubusercontent.com/5368008/43799805-242727fa-9a54-11e8-82db-5509b86d4d14.png)

It appears the search bar is contained in div with class of "_k _1a1e". Might it be as simple as modifying its display attribute from block to hidden?

![image](https://user-images.githubusercontent.com/5368008/43799881-520b0a74-9a54-11e8-8f5b-0d1f25daa84d.png)

**Comment by justinlittman** [comment]
Aware of this and working on a fix.

**Comment by jakelowen** [comment]
Sorry to be a pest, but I'd love to use this library on an upcoming project. If you want to describe the general approach you are considering to fix this and the CSV issue I am happy to work on it and submit a pull request. I have myself and another dev that could help.

**Comment by justinlittman** [comment]
Sorry for the delay, but I just started a new job. This should be fixed now.
